EXTRA_DIST += \
	datapath-windows/CodingStyle \
	datapath-windows/DESIGN \
	datapath-windows/Package/package.VcxProj \
	datapath-windows/Package/package.VcxProj.user \
	datapath-windows/include/OvsNetlink.h \
	datapath-windows/include/OvsPub.h \
	datapath-windows/misc/install.cmd \
	datapath-windows/misc/uninstall.cmd \
	datapath-windows/ovsext.sln \
	datapath-windows/ovsext/OvsActions.c \
	datapath-windows/ovsext/OvsAtomic.h \
	datapath-windows/ovsext/OvsBufferMgmt.c \
	datapath-windows/ovsext/OvsBufferMgmt.h \
	datapath-windows/ovsext/OvsChecksum.c \
	datapath-windows/ovsext/OvsChecksum.h \
	datapath-windows/ovsext/OvsDebug.c \
	datapath-windows/ovsext/OvsDebug.h \
	datapath-windows/ovsext/OvsDriver.c \
	datapath-windows/ovsext/OvsEth.h \
	datapath-windows/ovsext/OvsEvent.c \
	datapath-windows/ovsext/OvsEvent.h \
	datapath-windows/ovsext/OvsFlow.c \
	datapath-windows/ovsext/OvsFlow.h \
	datapath-windows/ovsext/OvsIoctl.c \
	datapath-windows/ovsext/OvsIoctl.h \
	datapath-windows/ovsext/OvsIpHelper.c \
	datapath-windows/ovsext/OvsIpHelper.h \
	datapath-windows/ovsext/OvsJhash.c \
	datapath-windows/ovsext/OvsJhash.h \
	datapath-windows/ovsext/OvsNetProto.h \
	datapath-windows/ovsext/OvsOid.c \
	datapath-windows/ovsext/OvsOid.h \
	datapath-windows/ovsext/OvsPacketIO.c \
	datapath-windows/ovsext/OvsPacketIO.h \
	datapath-windows/ovsext/OvsPacketParser.c \
	datapath-windows/ovsext/OvsPacketParser.h \
	datapath-windows/ovsext/OvsSwitch.c  \
	datapath-windows/ovsext/OvsSwitch.h \
	datapath-windows/ovsext/OvsTunnel.c \
	datapath-windows/ovsext/OvsTunnel.h \
	datapath-windows/ovsext/OvsTunnelFilter.c \
	datapath-windows/ovsext/OvsTunnelIntf.h \
	datapath-windows/ovsext/OvsTypes.h \
	datapath-windows/ovsext/OvsUser.c \
	datapath-windows/ovsext/OvsUser.h \
	datapath-windows/ovsext/OvsUtil.c  \
	datapath-windows/ovsext/OvsUtil.h \
	datapath-windows/ovsext/OvsVport.c \
	datapath-windows/ovsext/OvsVport.h \
	datapath-windows/ovsext/OvsVxlan.c \
	datapath-windows/ovsext/OvsVxlan.h \
	datapath-windows/ovsext/ovsext.inf \
	datapath-windows/ovsext/ovsext.rc \
	datapath-windows/ovsext/ovsext.vcxproj \
	datapath-windows/ovsext/ovsext.vcxproj.user \
	datapath-windows/ovsext/precomp.h \
	datapath-windows/ovsext/precompsrc.c
