EXTRA_DIST += \
	datapath-windows/CodingStyle \
	datapath-windows/DESIGN \
	datapath-windows/Package/package.VcxProj \
	datapath-windows/Package/package.VcxProj.user \
	datapath-windows/include/OvsDpInterfaceExt.h \
	datapath-windows/misc/install.cmd \
	datapath-windows/misc/uninstall.cmd \
	datapath-windows/misc/OVS.psm1 \
	datapath-windows/ovsext.sln \
	datapath-windows/ovsext/Datapath.c \
	datapath-windows/ovsext/Datapath.h \
	datapath-windows/ovsext/DpInternal.h\
	datapath-windows/ovsext/Actions.c \
	datapath-windows/ovsext/Atomic.h \
	datapath-windows/ovsext/BufferMgmt.c \
	datapath-windows/ovsext/BufferMgmt.h \
	datapath-windows/ovsext/Checksum.c \
	datapath-windows/ovsext/Checksum.h \
	datapath-windows/ovsext/Debug.c \
	datapath-windows/ovsext/Debug.h \
	datapath-windows/ovsext/Driver.c \
	datapath-windows/ovsext/Ethernet.h \
	datapath-windows/ovsext/Event.c \
	datapath-windows/ovsext/Event.h \
	datapath-windows/ovsext/Flow.c \
	datapath-windows/ovsext/Flow.h \
	datapath-windows/ovsext/IpHelper.c \
	datapath-windows/ovsext/IpHelper.h \
	datapath-windows/ovsext/Jhash.c \
	datapath-windows/ovsext/Jhash.h \
	datapath-windows/ovsext/Netlink/Netlink.c \
	datapath-windows/ovsext/Netlink/Netlink.h \
	datapath-windows/ovsext/Netlink/NetlinkBuf.c \
	datapath-windows/ovsext/Netlink/NetlinkBuf.h \
	datapath-windows/ovsext/Netlink/NetlinkError.h \
	datapath-windows/ovsext/Netlink/NetlinkProto.h \
	datapath-windows/ovsext/NetProto.h \
	datapath-windows/ovsext/Oid.c \
	datapath-windows/ovsext/Oid.h \
	datapath-windows/ovsext/PacketIO.c \
	datapath-windows/ovsext/PacketIO.h \
	datapath-windows/ovsext/PacketParser.c \
	datapath-windows/ovsext/PacketParser.h \
	datapath-windows/ovsext/Switch.c	 \
	datapath-windows/ovsext/Switch.h \
	datapath-windows/ovsext/Tunnel.c \
	datapath-windows/ovsext/Tunnel.h \
	datapath-windows/ovsext/TunnelFilter.c \
	datapath-windows/ovsext/TunnelIntf.h \
	datapath-windows/ovsext/Types.h \
	datapath-windows/ovsext/User.c \
	datapath-windows/ovsext/User.h \
	datapath-windows/ovsext/Util.c	\
	datapath-windows/ovsext/Util.h \
	datapath-windows/ovsext/Vport.c \
	datapath-windows/ovsext/Vport.h \
	datapath-windows/ovsext/Vxlan.c \
	datapath-windows/ovsext/Vxlan.h \
	datapath-windows/ovsext/ovsext.inf \
	datapath-windows/ovsext/ovsext.rc \
	datapath-windows/ovsext/ovsext.vcxproj \
	datapath-windows/ovsext/ovsext.vcxproj.user \
	datapath-windows/ovsext/precomp.h \
	datapath-windows/ovsext/precompsrc.c
