freebsd_build_task:

  freebsd_instance:
    matrix:
      image: freebsd-12-0-release-amd64
      image: freebsd-11-2-release-amd64
    cpu: 4
    memory: 8G

  env:
    DEPENDENCIES: automake libtool gmake gcc wget openssl
                  python py27-six py27-sphinx py27-openssl
                  python3 py36-six py36-openssl
    matrix:
      COMPILER: gcc
      COMPILER: clang

  prepare_script:
    - sysctl -w kern.coredump=0
    - pkg install -y ${DEPENDENCIES}

  configure_script:
    - ./boot.sh
    - ./configure CC=${COMPILER} MAKE=gmake OVS_CFLAGS='-Wall' --enable-Werror
                  || { cat config.log; exit 1; }

  build_script:
    - gmake -j8

  check_script:
    - gmake -j8 check TESTSUITEFLAGS=-j8 RECHECK=yes
                || { cat ./tests/testsuite.log; exit 1; }
