#!/bin/sh

# Generate list of files in debian/ to distribute.
(echo '# Automatically generated by boot.sh (from Git tree).' &&
 echo 'EXTRA_DIST = \' &&
 cd debian && git ls-files | grep -v '^\.gitignore$' | 
 sed -e 's/\(.*\)/	\1 \\/' -e '$s/ \\//') > debian/Makefile.am

# Bootstrap configure system from .ac/.am files
autoreconf --install -I config --force
