debian/ifupdown.sh usr/share/openvswitch/scripts
etc/bash_completion.d/ovs-vsctl-bashcomp.bash
usr/bin/ovs-dpctl
usr/bin/ovs-dpctl-top
usr/bin/ovs-pcap
usr/bin/ovs-tcpdump
usr/bin/ovs-tcpundump
usr/bin/ovs-vlan-test
usr/bin/ovs-vsctl
usr/bin/ovsdb-tool
usr/sbin/ovs-vswitchd
usr/sbin/ovsdb-server
usr/share/openvswitch/scripts/ovs-check-dead-ifs
usr/share/openvswitch/scripts/ovs-ctl
usr/share/openvswitch/scripts/ovs-save
usr/share/openvswitch/vswitch.ovsschema
