.TH ovs-switch-setup 8 "June 2008" "Open vSwitch" "Open vSwitch Manual"

.SH NAME
ovs\-switch\-setup \- interactive setup for Open vSwitch switch

.SH SYNOPSIS
.B ovs\-switch\-setup

.SH DESCRIPTION
The \fBovs\-switch\-setup\fR program is an interactive program that
assists the system administrator in configuring an Open vSwitch switch,
including the underlying public key infrastructure (PKI).

.SH OPTIONS
ovs\-switch\-setup does not accept any command-line options.

.SH FILES
.IP /etc/default/openvswitch-switch
Main configuration file for Open vSwitch switch.

.IP /etc/openvswitch-switch/cacert.pem
Default location of CA certificate for OpenFlow controllers.

.IP /etc/openvswitch-switch/of0-cert.pem
Default location of certificate for the Open vSwitch switch's private key.

.IP /etc/openvswitch-switch/of0-privkey.pem
Default location of the Open vSwitch switch's private key.  This file
should be readable only by \fBroot\fR.

.IP /etc/openvswitch-switch/of0-req.pem
Default location of certificate request for the Open vSwitch switch's
certificate.  This file is not used after the signed certificate
(typically \fB/etc/openvswitch-switch/of0-cert.pem\fR, above) has been
obtained from the OpenFlow PKI server.

.SH "SEE ALSO"

.BR ovs\-dpctl (8),
.BR ovs-pki (8),
.BR ovs-openflowd (8)
