noinst_HEADERS += \
	include/command-line.h \
	include/compiler.h \
	include/csum.h \
	include/daemon.h \
	include/dhcp-client.h \
	include/dhcp.h \
	include/dirs.h \
	include/dynamic-string.h \
	include/dpif.h \
	include/fatal-signal.h \
	include/fault.h \
	include/flow.h \
	include/hash.h \
	include/learning-switch.h \
	include/list.h \
	include/mac-learning.h \
	include/netdev.h \
	include/netlink-protocol.h \
	include/netlink.h \
	include/nicira-ext.h \
	include/ofpbuf.h \
	include/ofp-print.h \
	include/openflow.h \
	include/openflow-netlink.h \
	include/packets.h \
	include/poll-loop.h \
	include/port-array.h \
	include/queue.h \
	include/random.h \
	include/rconn.h \
	include/sat-math.h \
	include/socket-util.h \
	include/type-props.h \
	include/timeval.h \
	include/stp.h \
	include/util.h \
	include/vconn.h \
	include/vconn-provider.h \
	include/vconn-ssl.h \
	include/vconn-stream.h \
	include/vlog-socket.h \
	include/vlog-modules.def \
	include/vlog.h \
	include/xtoxll.h
