#! /bin/bash

#Iterate through each port of every bridge and print
#the port statistics

for bridge in `ovs-vsctl -- --real list-br`
do
    echo "${bridge} : "
    echo "  ${bridge} : `ovs-vsctl get interface ${bridge} statistics`"
    for iface in `ovs-vsctl list-ifaces ${bridge}`
    do
        echo "  ${iface} : `ovs-vsctl get interface ${iface} statistics`"
    done
    echo -e "\n"
done
