.\" -*- nroff -*-
.TH ovsdbmonitor 1 "May 2011" "Open vSwitch" "Open vSwitch Manual"
.
.SH NAME
ovsdbmonitor \- GUI tool for monitoring Open vSwitch installations
.
.SH SYNOPSIS
\fBovsdbmonitor\fR
.
.SH DESCRIPTION
The \fBovsdbmonitor\fR program is a Qt-based GUI tool for monitoring
and troubleshooting Open vSwitch.  It presents GUI tables that
graphically represent an Open vSwitch kernel flow table (similar to
\fBovs\-dpctl dump\-flows\fR) and Open vSwitch database contents
(similar to \fBovs\-vsctl list \fItable\fR).
.SH "SEE ALSO"
.
\fBovsdb\-server\fR(1),
\fBovsdb\-client\fR(1),
and the OVSDB specification.
