# Spec file for vswitch and related programs.

# Copyright (C) 2009 Nicira Networks, Inc.
#
# Copying and distribution of this file, with or without modification,
# are permitted in any medium without royalty provided the copyright
# notice and this notice are preserved.  This file is offered as-is,
# without warranty of any kind.

# When building, the rpmbuild command line should define
# vswitch_version, xen_version, and build_number using -D arguments.
# for example:
#
#    rpmbuild -D "vswitch_version 0.8.9~1+build123" -D "xen_version 2.6.18-128.1.1.el5.xs5.1.0.483.1000xen" -D "build_number --with-build-number=123" -bb /usr/src/redhat/SPECS/vswitch-xen.spec
#
%define version %{vswitch_version}-%{xen_version}

Name: vswitch
Summary: Virtual switch
Group: System Environment/Daemons
URL: http://www.openvswitch.org/
Version: %{vswitch_version}

# The entire source code is ASL 2.0 except datapath/ which is GPLv2
License: ASL 2.0 and GPLv2
Release: 1
Source: openvswitch-%{vswitch_version}.tar.gz
Buildroot: /tmp/vswitch-xen-rpm
Requires: kernel-xen = %(echo '%{xen_version}' | sed 's/xen$//')
# The following Conflicts prevents the "vswitch" package generated by
# this spec file from installing at the same time as the "openvswitch"
# package shipped with XenServer 5.5.900.  In fact, the packages
# contain some files with identical names anyhow, so they will not
# coexist, but adding an explicit Conflicts makes this conflict more
# obvious.
Conflicts: openvswitch

%description
The vswitch provides standard network bridging functions augmented with
support for the OpenFlow protocol for remote per-flow control of
traffic.

%prep
%setup -q -n openvswitch-%{vswitch_version}

%build
./configure --prefix=/usr --sysconfdir=/etc --localstatedir=%{_localstatedir} --with-l26=/lib/modules/%{xen_version}/build --enable-ssl %{build_number}
make %{_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT
make install DESTDIR=$RPM_BUILD_ROOT
install -d -m 755 $RPM_BUILD_ROOT/etc
install -d -m 755 $RPM_BUILD_ROOT/etc/init.d
install -m 755 xenserver/etc_init.d_vswitch \
         $RPM_BUILD_ROOT/etc/init.d/vswitch
install -m 755 xenserver/etc_init.d_vswitch-xapi-update \
         $RPM_BUILD_ROOT/etc/init.d/vswitch-xapi-update
install -d -m 755 $RPM_BUILD_ROOT/etc/sysconfig
install -d -m 755 $RPM_BUILD_ROOT/etc/logrotate.d
install -m 755 xenserver/etc_logrotate.d_vswitch \
         $RPM_BUILD_ROOT/etc/logrotate.d/vswitch
install -d -m 755 $RPM_BUILD_ROOT/etc/profile.d
install -m 755 xenserver/etc_profile.d_vswitch.sh \
         $RPM_BUILD_ROOT/etc/profile.d/vswitch.sh
install -d -m 755 $RPM_BUILD_ROOT/etc/xapi.d/plugins
install -m 755 xenserver/etc_xapi.d_plugins_vswitch-cfg-update \
         $RPM_BUILD_ROOT/etc/xapi.d/plugins/vswitch-cfg-update
install -d -m 755 $RPM_BUILD_ROOT/usr/share/vswitch/scripts
install -m 755 xenserver/opt_xensource_libexec_interface-reconfigure \
             $RPM_BUILD_ROOT/usr/share/vswitch/scripts/interface-reconfigure
install -m 755 xenserver/etc_xensource_scripts_vif \
             $RPM_BUILD_ROOT/usr/share/vswitch/scripts/vif
install -m 755 xenserver/usr_share_vswitch_scripts_dump-vif-details \
               $RPM_BUILD_ROOT/usr/share/vswitch/scripts/dump-vif-details
install -m 755 xenserver/usr_share_vswitch_scripts_refresh-xs-network-uuids \
               $RPM_BUILD_ROOT/usr/share/vswitch/scripts/refresh-xs-network-uuids
install -m 755 xenserver/usr_sbin_xen-bugtool \
             $RPM_BUILD_ROOT/usr/share/vswitch/scripts/xen-bugtool
install -m 755 xenserver/usr_sbin_brctl \
             $RPM_BUILD_ROOT/usr/share/vswitch/scripts/brctl
install -m 755 xenserver/usr_share_vswitch_scripts_sysconfig.template \
         $RPM_BUILD_ROOT/usr/share/vswitch/scripts/sysconfig.template
install -m 644 \
        xenserver/usr_lib_xsconsole_plugins-base_XSFeatureVSwitch.py \
               $RPM_BUILD_ROOT/usr/share/vswitch/scripts/XSFeatureVSwitch.py

install -d -m 755 $RPM_BUILD_ROOT/lib/modules/%{xen_version}/kernel/net/vswitch
find datapath/linux-2.6 -name *.ko -exec install -m 755  \{\} $RPM_BUILD_ROOT/lib/modules/%{xen_version}/kernel/net/vswitch \;

# Get rid of stuff we don't want to make RPM happy.
rm \
    $RPM_BUILD_ROOT/usr/bin/ovs-controller \
    $RPM_BUILD_ROOT/usr/bin/ovs-discover \
    $RPM_BUILD_ROOT/usr/bin/ovs-kill \
    $RPM_BUILD_ROOT/usr/bin/ovs-openflowd \
    $RPM_BUILD_ROOT/usr/bin/ovs-pki \
    $RPM_BUILD_ROOT/usr/bin/ovs-wdt \
    $RPM_BUILD_ROOT/usr/sbin/ovs-monitor \
    $RPM_BUILD_ROOT/usr/share/man/man8/ovs-controller.8 \
    $RPM_BUILD_ROOT/usr/share/man/man8/ovs-discover.8 \
    $RPM_BUILD_ROOT/usr/share/man/man8/ovs-kill.8 \
    $RPM_BUILD_ROOT/usr/share/man/man8/ovs-openflowd.8 \
    $RPM_BUILD_ROOT/usr/share/man/man8/ovs-pki.8
rm -f $RPM_BUILD_ROOT/lib/modules/%{xen_version}/kernel/net/vswitch/veth_mod.ko
rm -r \
    $RPM_BUILD_ROOT/usr/share/openvswitch/commands

install -d -m 755 $RPM_BUILD_ROOT/var/lib/openvswitch

%clean
rm -rf $RPM_BUILD_ROOT

%post
if [ ! -f /etc/xensource-inventory ]; then
    printf "XenSource inventory not present in /etc/xensource-inventory"
    exit 1
fi

if [ "$1" = "1" ]; then
    if md5sum -c --status <<EOF
ca141d60061dcfdade73e75abc6529b5  /usr/sbin/brctl
b8e9835862ef1a9cec2a3f477d26c989  /etc/xensource/scripts/vif
51970ad613a3996d5997e18e44db47da  /opt/xensource/libexec/interface-reconfigure
5654c8c36699fcc8744ca9cd5b855414  /usr/sbin/xen-bugtool
EOF
    then
        printf "\nVerified host scripts from XenServer 5.5.0.\n\n"
    elif md5sum -c --status <<EOF
ca141d60061dcfdade73e75abc6529b5  /usr/sbin/brctl
b8e9835862ef1a9cec2a3f477d26c989  /etc/xensource/scripts/vif
ce451d3c985fd1db6497a363f0d9dedb  /opt/xensource/libexec/interface-reconfigure
2b53f500431fcba5276c896e9e4281b9  /usr/sbin/xen-bugtool
EOF
    then
        printf "\nVerified host scripts from XenServer 5.5.900.\n\n"
    else
cat <<EOF

The original XenServer scripts replaced by this package are not those
of any supported version of XenServer.  This could lead to unexpected
behavior of your server.  Unless you are sure you know what you are
doing, it is highly recommended that you remove this package
immediately after the install completes, which will restore the
XenServer scripts that you were previously using.

EOF
    fi
fi

if test ! -e /var/lib/openvswitch/dbcache; then
    if test "$1" = 1; then
        printf "Creating xapi database cache...  "
    else
        printf "warning: Open vSwitch is being re-installed or upgraded,\n"
        printf "         but the xapi database cache is missing.\n"
        printf "Re-creating xapi database cache...  "
    fi

    if /usr/share/vswitch/scripts/interface-reconfigure rewrite; then
        printf "done.\n"
    else
        printf "FAILED\n"
        printf "Open vSwitch can only be installed on a XenServer that\n"
        printf "has connectivity to xapi on the pool master.  Please\n"
        printf "fix connectivity to the pool master, then try again.\n"
        exit 1
    fi
fi

# Ensure that modprobe will find our modules.
depmod %{xen_version}

if grep -F net.ipv4.conf.all.arp_filter /etc/sysctl.conf >/dev/null 2>&1; then :; else
    cat >>/etc/sysctl.conf <<EOF
# This works around an issue in xhad, which binds to a particular
# Ethernet device, which in turn causes ICMP port unreachable messages
# if packets are received are on the wrong interface, which in turn
# can happen if we send out ARP replies on every interface (as Linux
# does by default) instead of just on the interface that has the IP
# address being ARPed for, which this sysctl setting in turn works
# around.
#
# Bug #1378.
net.ipv4.conf.all.arp_filter = 1
EOF
fi

# Ensure ovs-vswitchd.conf exists
touch /etc/ovs-vswitchd.conf

# Create default or update existing /etc/sysconfig/vswitch.
SYSCONFIG=/etc/sysconfig/vswitch
TEMPLATE=/usr/share/vswitch/scripts/sysconfig.template
if [ ! -e $SYSCONFIG ]; then
    cp $TEMPLATE $SYSCONFIG
else
    for var in $(awk -F'[ :]' '/^# [_A-Z0-9]+:/{print $2}' $TEMPLATE)
    do
        if ! grep $var $SYSCONFIG >/dev/null 2>&1; then
            echo >> $SYSCONFIG
            sed -n "/$var:/,/$var=/p" $TEMPLATE >> $SYSCONFIG
        fi
    done
fi

# Replace XenServer files by our versions.
mkdir -p /usr/lib/vswitch/xs-original \
    || printf "Could not create script backup directory.\n"
for f in \
    /opt/xensource/libexec/interface-reconfigure \
    /etc/xensource/scripts/vif \
    /usr/sbin/xen-bugtool \
    /usr/sbin/brctl
do
    s=$(basename "$f")
    t=$(readlink "$f")
    if [ "$t" != "/usr/share/vswitch/scripts/$s" ]; then
        mv "$f" /usr/lib/vswitch/xs-original/ \
            || printf "Could not save original XenServer $s script\n"
        ln -s "/usr/share/vswitch/scripts/$s" "$f" \
            || printf "Could not link to vSwitch $s script\n"
    fi
done

# Install xsconsole plugin
plugin=$(readlink /usr/lib/xsconsole/plugins-base/XSFeatureVSwitch.py)
if [ "$plugin" != "/usr/share/vswitch/scripts/XSFeatureVSwitch.py" ]; then
    rm -f /usr/lib/xsconsole/plugins-base/XSFeatureVSwitch.py
    ln -s /usr/share/vswitch/scripts/XSFeatureVSwitch.py /usr/lib/xsconsole/plugins-base/ || printf "Could not link to vSswitch xsconsole plugin.\n"
fi

# Ensure all required services are set to run
for s in vswitch vswitch-xapi-update; do
    if chkconfig --list $s >/dev/null 2>&1; then
        chkconfig --del $s || printf "Could not remove $s init script."
    fi
    chkconfig --add $s || printf "Could not add $s init script."
    chkconfig $s on || printf "Could not enable $s init script."
done

if [ "$1" = "1" ]; then    # $1 = 2 for upgrade
    printf "\nYou MUST reboot the server NOW to complete the change to the\n"
    printf "the vSwitch.  Attempts to modify networking on the server\n"
    printf "or any hosted VM will fail until after the reboot and could\n"
    printf "leave the server in an state requiring manual recovery.\n\n"
else
    printf "\nTo use the new vSwitch, you should reboot the server\n"
    printf "now.  Failure to do so may result in incorrect operation.\n\n"
fi

%preun
if [ "$1" = "0" ]; then     # $1 = 1 for upgrade
    for s in vswitch vswitch-xapi-update; do
        chkconfig --del $s || printf "Could not remove $s init script."
    done
fi


%postun
if [ "$1" = "0" ]; then     # $1 = 1 for upgrade

    rm -f /usr/lib/xsconsole/plugins-base/XSFeatureVSwitch.py \
        /usr/lib/xsconsole/plugins-base/XSFeatureVSwitch.pyc \
        /usr/lib/xsconsole/plugins-base/XSFeatureVSwitch.pyo \
        || printf "Could not remove vSwitch xsconsole plugin.\n"

    # Restore original XenServer scripts
    for f in \
        /opt/xensource/libexec/interface-reconfigure \
        /etc/xensource/scripts/vif \
        /usr/sbin/xen-bugtool \
        /usr/sbin/brctl
    do
        s=$(basename "$f")
        if [ ! -f "/usr/lib/vswitch/xs-original/$s" ]; then
            printf "Original XenServer $s script not present in /usr/lib/vswitch/xs-original\n"
            printf "Could not restore original XenServer script.\n"
        else
            (rm -f "$f" \
                && mv "/usr/lib/vswitch/xs-original/$s" "$f") \
                || printf "Could not restore original XenServer $s script.\n"
        fi
    done

    # Remove all configuration files
    rm -f /etc/ovs-vswitchd.conf
    rm -f /etc/sysconfig/vswitch
    rm -f /etc/ovs-vswitchd.cacert
    rm -f /var/lib/openvswitch/dbcache

    printf "\nYou MUST reboot the server now to complete the change to\n"
    printf "standard Xen networking.  Attempts to modify networking on the\n"
    printf "server or any hosted VM will fail until after the reboot and\n"
    printf "could leave the server in a state requiring manual recovery.\n\n"
fi


%files
%defattr(-,root,root)
/etc/init.d/vswitch
/etc/init.d/vswitch-xapi-update
/etc/xapi.d/plugins/vswitch-cfg-update
/etc/logrotate.d/vswitch
/etc/profile.d/vswitch.sh
/lib/modules/%{xen_version}/kernel/net/vswitch/openvswitch_mod.ko
/lib/modules/%{xen_version}/kernel/net/vswitch/brcompat_mod.ko
/usr/share/vswitch/scripts/dump-vif-details
/usr/share/vswitch/scripts/refresh-xs-network-uuids
/usr/share/vswitch/scripts/interface-reconfigure
/usr/share/vswitch/scripts/vif
/usr/share/vswitch/scripts/xen-bugtool
/usr/share/vswitch/scripts/XSFeatureVSwitch.py
/usr/share/vswitch/scripts/brctl
/usr/share/vswitch/scripts/sysconfig.template
# Following two files are generated automatically by rpm.  We don't
# really need them and they won't be used on the XenServer, but there
# isn't an obvious place to get rid of them since they are generated
# after the install script runs.  Since they are small, we just
# include them.
/usr/share/vswitch/scripts/XSFeatureVSwitch.pyc
/usr/share/vswitch/scripts/XSFeatureVSwitch.pyo
/usr/sbin/ovs-brcompatd
/usr/sbin/ovs-vswitchd
/usr/bin/ovs-appctl
/usr/bin/ovs-cfg-mod
/usr/bin/ovs-dpctl
/usr/bin/ovs-ofctl
/usr/bin/ovs-vsctl
/usr/share/man/man5/ovs-vswitchd.conf.5.gz
/usr/share/man/man8/ovs-appctl.8.gz
/usr/share/man/man8/ovs-brcompatd.8.gz
/usr/share/man/man8/ovs-cfg-mod.8.gz
/usr/share/man/man8/ovs-dpctl.8.gz
/usr/share/man/man8/ovs-ofctl.8.gz
/usr/share/man/man8/ovs-vsctl.8.gz
/usr/share/man/man8/ovs-vswitchd.8.gz
/var/lib/openvswitch
